// Curated famous false friends from false-friends.html
export const FF_CURATED = [
  // EN <-> ES
  { langs: ['en','es'], a: 'embarrassed',   b: 'embarazada',
    meaningA: 'feeling shame or self-consciousness',
    meaningB: 'pregnant',
    note: 'A famous trap - the original sin of Spanish learners.' },
  { langs: ['en','es'], a: 'library',       b: 'librería',
    meaningA: 'place that lends books',
    meaningB: 'bookstore (the library is *biblioteca*)' },
  { langs: ['en','es'], a: 'exit',          b: 'éxito',
    meaningA: 'a way out',
    meaningB: 'success' },
  { langs: ['en','es'], a: 'actually',      b: 'actualmente',
    meaningA: 'in fact, really',
    meaningB: 'currently, at present' },
  { langs: ['en','es'], a: 'assist',        b: 'asistir',
    meaningA: 'help someone',
    meaningB: 'to attend (a meeting, class)' },
  { langs: ['en','es'], a: 'carpet',        b: 'carpeta',
    meaningA: 'rug, floor covering',
    meaningB: 'folder' },
  { langs: ['en','es'], a: 'constipated',   b: 'constipado',
    meaningA: 'unable to defecate',
    meaningB: 'having a cold' },
  { langs: ['en','es'], a: 'introduce',     b: 'introducir',
    meaningA: 'to make someone known',
    meaningB: 'to insert / put inside' },
  { langs: ['en','es'], a: 'molest',        b: 'molestar',
    meaningA: 'to abuse sexually',
    meaningB: 'to bother, annoy' },
  { langs: ['en','es'], a: 'realize',       b: 'realizar',
    meaningA: 'to become aware of',
    meaningB: 'to carry out, perform' },
  { langs: ['en','es'], a: 'rope',          b: 'ropa',
    meaningA: 'thick cord',
    meaningB: 'clothes, clothing' },
  { langs: ['en','es'], a: 'soap',          b: 'sopa',
    meaningA: 'cleaning substance',
    meaningB: 'soup' },
  { langs: ['en','es'], a: 'sympathy',      b: 'simpatía',
    meaningA: 'compassion for sorrow',
    meaningB: 'friendliness, charm' },
  { langs: ['en','es'], a: 'sensible',      b: 'sensible',
    meaningA: 'reasonable, practical',
    meaningB: 'sensitive (emotional)' },
  { langs: ['en','es'], a: 'fabric',        b: 'fábrica',
    meaningA: 'cloth, textile',
    meaningB: 'factory' },

  // EN <-> DE
  { langs: ['en','de'], a: 'gift',          b: 'Gift',
    meaningA: 'a present',
    meaningB: 'poison',
    note: 'A famously dangerous false friend.' },
  { langs: ['en','de'], a: 'bald',          b: 'bald',
    meaningA: 'hairless',
    meaningB: 'soon' },
  { langs: ['en','de'], a: 'become',        b: 'bekommen',
    meaningA: 'to come to be',
    meaningB: 'to receive, get' },
  { langs: ['en','de'], a: 'chef',          b: 'Chef',
    meaningA: 'cook',
    meaningB: 'boss, head' },
  { langs: ['en','de'], a: 'handy',         b: 'Handy',
    meaningA: 'convenient',
    meaningB: 'mobile phone (false anglicism)' },
  { langs: ['en','de'], a: 'rat',           b: 'Rat',
    meaningA: 'rodent',
    meaningB: 'advice, council' },
  { langs: ['en','de'], a: 'billion',       b: 'Billion',
    meaningA: '10⁹ (one thousand million)',
    meaningB: '10¹² (one million million)' },
  { langs: ['en','de'], a: 'sympathetic',   b: 'sympathisch',
    meaningA: 'showing pity',
    meaningB: 'likeable' },

  // EN <-> FR
  { langs: ['en','fr'], a: 'actually',      b: 'actuellement',
    meaningA: 'in fact, really',
    meaningB: 'currently, at present' },
  { langs: ['en','fr'], a: 'assist',        b: 'assister',
    meaningA: 'help',
    meaningB: 'to attend (an event)' },
  { langs: ['en','fr'], a: 'attend',        b: 'attendre',
    meaningA: 'to go to (an event)',
    meaningB: 'to wait for' },
  { langs: ['en','fr'], a: 'eventually',    b: 'éventuellement',
    meaningA: 'in the end, at last',
    meaningB: 'possibly, perhaps' },
  { langs: ['en','fr'], a: 'library',       b: 'librairie',
    meaningA: 'place that lends books',
    meaningB: 'bookstore' },
  { langs: ['en','fr'], a: 'preservative',  b: 'préservatif',
    meaningA: 'food additive',
    meaningB: 'condom',
    note: 'Asking for "préservatifs" at a French bakery is awkward.' },
  { langs: ['en','fr'], a: 'sensible',      b: 'sensible',
    meaningA: 'reasonable',
    meaningB: 'sensitive, easily moved' },
  { langs: ['en','fr'], a: 'pain',          b: 'pain',
    meaningA: 'physical suffering',
    meaningB: 'bread' },
  { langs: ['en','fr'], a: 'coin',          b: 'coin',
    meaningA: 'metal money',
    meaningB: 'corner' },
  { langs: ['en','fr'], a: 'route',         b: 'route',
    meaningA: 'a path/way (informal)',
    meaningB: 'road, highway' },

  // EN <-> IT
  { langs: ['en','it'], a: 'camera',        b: 'camera',
    meaningA: 'photo device',
    meaningB: 'room (camera is *macchina fotografica*)' },
  { langs: ['en','it'], a: 'factory',       b: 'fattoria',
    meaningA: 'manufacturing plant',
    meaningB: 'farm' },
  { langs: ['en','it'], a: 'pretend',       b: 'pretendere',
    meaningA: 'to fake',
    meaningB: 'to demand, claim' },
  { langs: ['en','it'], a: 'parents',       b: 'parenti',
    meaningA: 'mother and father',
    meaningB: 'relatives in general' },
  { langs: ['en','it'], a: 'morbid',        b: 'morbido',
    meaningA: 'unhealthily preoccupied',
    meaningB: 'soft' },

  // EN <-> PT
  { langs: ['en','pt'], a: 'pasta',         b: 'pasta',
    meaningA: 'Italian noodles',
    meaningB: 'folder, briefcase' },
  { langs: ['en','pt'], a: 'push',          b: 'puxar',
    meaningA: 'press away from you',
    meaningB: 'to pull (toward you)',
    note: 'On Portuguese doors, "puxe" means PULL - opposite of push!' },
  { langs: ['en','pt'], a: 'parents',       b: 'parentes',
    meaningA: 'mother and father',
    meaningB: 'relatives' },
  { langs: ['en','pt'], a: 'data',          b: 'data',
    meaningA: 'information',
    meaningB: 'a date (calendar)' },

  // ES <-> IT (extremely tricky - same-Romance trap)
  { langs: ['es','it'], a: 'burro',         b: 'burro',
    meaningA: 'donkey',
    meaningB: 'butter',
    note: 'Order *burro con pan* in Italy → butter with bread; in Spain → donkey with bread.' },
  { langs: ['es','it'], a: 'aceite',        b: 'aceto',
    meaningA: 'oil',
    meaningB: 'vinegar' },
  { langs: ['es','it'], a: 'subir',         b: 'subire',
    meaningA: 'to go up',
    meaningB: 'to undergo, suffer' },
  { langs: ['es','it'], a: 'embarazada',    b: 'imbarazzata',
    meaningA: 'pregnant',
    meaningB: 'embarrassed' },
  { langs: ['es','it'], a: 'salir',         b: 'salire',
    meaningA: 'to go out',
    meaningB: 'to climb up' },

  // ES <-> PT
  { langs: ['es','pt'], a: 'exquisito',     b: 'esquisito',
    meaningA: 'refined, exquisite',
    meaningB: 'weird, strange' },
  { langs: ['es','pt'], a: 'embarazada',    b: 'embaraçada',
    meaningA: 'pregnant',
    meaningB: 'embarrassed (mostly)' },
  { langs: ['es','pt'], a: 'oficina',       b: 'oficina',
    meaningA: 'office',
    meaningB: 'workshop, garage' },
  { langs: ['es','pt'], a: 'rojo',          b: 'roxo',
    meaningA: 'red',
    meaningB: 'purple' },

  // FR <-> IT
  { langs: ['fr','it'], a: 'magasin',       b: 'magazzino',
    meaningA: 'shop, store',
    meaningB: 'warehouse, storeroom' },

  // DE <-> SV / NL / DA
  { langs: ['de','sv'], a: 'rolig',         b: 'rolig',
    meaningA: 'calm (DA/NO)',
    meaningB: 'fun, funny (SV)' },

  // SV <-> DA
  { langs: ['sv','da'], a: 'rolig',         b: 'rolig',
    meaningA: 'fun, funny',
    meaningB: 'calm, quiet' },
  { langs: ['sv','da'], a: 'frokost',       b: 'frokost',
    meaningA: '(SV: frukost) breakfast',
    meaningB: 'lunch' },

  // RU <-> PL
  { langs: ['ru','pl'], a: 'запомнить',     b: 'zapomnieć',
    meaningA: 'to remember',
    meaningB: 'to forget',
    note: 'A spectacular Slavic mirror-image false friend.' },
  { langs: ['ru','cs'], a: 'красный',       b: 'krásný',
    meaningA: 'red',
    meaningB: 'beautiful' },

  // HI <-> UR
  { langs: ['hi','ur'], a: 'अच्छा',          b: 'اچھا',
    meaningA: 'good (informal exclamation: I see)',
    meaningB: 'good (same root, slight register drift)',
    note: 'Often considered the same word - register & script differ.' },

  // EN <-> JA
  { langs: ['en','ja'], a: 'mansion',       b: 'マンション (manshon)',
    meaningA: 'large luxurious house',
    meaningB: 'an ordinary apartment building' },
  { langs: ['en','ja'], a: 'smart',         b: 'スマート (sumāto)',
    meaningA: 'intelligent',
    meaningB: 'slim, slender' },
  { langs: ['en','ja'], a: 'cunning',       b: 'カンニング (kanningu)',
    meaningA: 'crafty, sly',
    meaningB: 'cheating on a test' }
];
